import pickle
from tkinter import *

def find_absentees(class_division,file_name):
	# To retreive all students from the given division
	#class_division = input("Enter the Division of the class (C or D): ")
	write_file = open("./global/9"+class_division+".obj", 'rb')
	all_students = pickle.load(write_file)

	# To read the contents from the given attendance list
	#file_name = input("\nEnter the input filename: ")
	with open('./testing_data/'+file_name+'.csv', encoding='utf-16') as f:
		contents = f.read()

	# To traverse and get the names
	student_list = []
	for line in contents.split('\n'):
		items = line.split('\t')
		student_list.append(items[0])

	# To remove duplicates
	students_list = list(set(student_list[2:]))

	# To remove the empty string
	students_list.remove('')

	# To store the sorted list
	students_list = sorted(students_list)
	
	# To print the Absentees list
	res = "Absentees in Maths Class are:"
	for student in all_students:
		if(student not in students_list):
			res += "\n"+ student
	return(res)

# create root window
root = Tk()
root.title("Trace Latecomers")
root.geometry('400x600')
 
# adding a label to the root window
division_lbl = Label(root, text = "Enter the Class Division (C or D): ")
division_box = Entry(root, width=23)
division_lbl.grid(column=0, row=0, sticky = W, pady = 4)
division_box.grid(column=1, row=0, sticky = W, pady = 4)

# To enter the filename generated by MS Teams
filename_lbl = Label(root, text="Enter the Filename: ")
filename_box = Entry(root, width=23)
filename_lbl.grid(column=0, row=1, sticky = W, pady = 2)
filename_box.grid(column=1, row=1, sticky = W, pady = 2)

# Output text
output_text = Text(root, height = 33, width = 55)
output_text.grid(column=0, row=3, sticky=E, rowspan=10, columnspan=2, pady=3)

# Resets and prints the result
def clicked():
	output_text.delete("1.0","end")
	res = find_absentees(division_box.get(),filename_box.get())
	output_text.insert(tk.END, res)
 
btn = Button(root, text="TRACE" ,fg="black", command=clicked)
btn.grid(column=0, row=2, sticky=W+E, columnspan=2, pady=2)
 
# Running the GUI
root.mainloop()